export { heroSection, heroSectionType } from "./heroSection";
export { trustedBySectionType } from "./trustedBySection";
export { painPointsSectionType } from "./painPointsSection";
export { servicesShowcaseSectionType } from "./servicesShowcaseSection";
export { resultsSectionType } from "./resultsSection";
export { processSectionType } from "./processSection";
export { partnersSectionType } from "./partnersSection";
export { ctaSection, ctaSectionType } from "./ctaSection";
export { technicalDepthSectionType } from "./technicalDepthSection";
export { testimonialSectionType } from "./testimonialSection";
export { latestInsightsSectionType } from "./latestInsightsSection";
