import { defineEnableDraftMode } from "next-sanity/draft-mode";
import { client } from "@/sanity/lib/client";

/**
 * Enables Next.js draft mode when opened from the Sanity Presentation tool.
 * The Presentation tool calls this route with a secret generated by
 * next-sanity; the token validates the request against the Sanity project.
 */
export const { GET } = defineEnableDraftMode({
  client: client.withConfig({ token: process.env.SANITY_API_READ_TOKEN }),
});
