// ============================================
// Object Types (reusable schema objects)
// ============================================
import {
  link,
  button,
  seo,
  blockContent,
  richTextBlock,
  keyTakeawaysBlock,
  statsRowBlock,
  tableBlock,
  comparisonCardsBlock,
  calloutBlock,
  prosConsBlock,
  codeBlock,
  faqBlock,
  ctaBlock,
  gradientTitleBlock,
  imageBlock,
  dividerBlock,
} from "./objects";

// ============================================
// Document Types (e.g. post page builder)
// ============================================
import { post } from "./documents";

// ============================================
// Page Types (document types for pages)
// ============================================
import { calendlyBooking } from "./calendlyBooking";
import {
  heroSection,
  trustedBySection,
  painPointsSection,
  servicesShowcaseSection,
  resultsSection,
  processSection,
  partnersSection,
  ctaSection,
  technicalDepthSection,
} from "./components";
import {
  workPageHeroSection,
  workPageCaseStudiesSection,
  workPageCtaSection,
} from "./pages/workPage";
import {
  partnersPageHeroSection,
  partnersPageWhyOurPartnershipSection,
  partnersPagePartnersGridSection,
  partnersPageCtaSection,
} from "./pages/partnersPage";
import {
  aboutPageHeroSection,
  aboutPageWhyDifferentSection,
  aboutPageOurStorySection,
  aboutPageOurValuesSection,
  aboutPageMeetTheTeamSection,
  aboutPageTrustedPartnershipsSection,
  aboutPageCtaSection,
} from "./pages/aboutPage";
import {
  contactPageBookingNested,
  contactPageMessageNested,
  contactPageHeroSection,
  contactPageCardsSection,
  contactPageBookingGroupSection,
  contactPageMapSection,
  contactPageFaqSection,
} from "./pages/contactPage";
import {
  migratePageHeroSection,
  migratePagePlatformsSection,
  migratePageRisksProtectionSection,
  migratePageProcessSection,
  migratePageResultsSection,
  migratePageCtaSection,
} from "./pages/migratePage";
import {
  merchPageHeroSection,
  merchPageQualityShowcaseSection,
  merchPageNewsletterSection,
} from "./pages/merchPage";
import {
  blogPageHeroSection,
  blogPageFeaturedArticleSection,
  blogPageArticlesGridSection,
  blogPageNewsletterCtaSection,
} from "./pages/blogPage";
import {
  allPackagesPageHeroSection,
  allPackagesPagePackagesSection,
  allPackagesPageFaqSection,
} from "./pages/allPackagesPage";
import {
  packageDetailPagePackageInfoSection,
  packageDetailPageHeroButtonsSection,
  packageDetailPageBestForSection,
  packageDetailPageIdealForSection,
  packageDetailPageHighlightsSection,
  packageDetailPageMoreDeliverablesSection,
  packageDetailPageIncludedListSection,
  packageDetailPageIncludedCategoriesSection,
  packageDetailPageProcessStepsSection,
  packageDetailPageFaqListSection,
  packageDetailPageReviewsListSection,
  packageDetailPageTabLabelsSection,
  packageDetailPageAddOnsSection,
  packageDetailPageCaseStudiesBannerSection,
} from "./pages/packageDetailPage";
import {
  vippsHurtigkassePageHeroSection,
  vippsHurtigkassePageFeaturesSection,
  vippsHurtigkassePageHowToGetStartedSection,
  vippsHurtigkassePagePricingSection,
  vippsHurtigkassePageOrderFormSection,
  vippsHurtigkassePageSupportSection,
} from "./pages/vippsHurtigkassePage";
import {
  shopifyDevelopmentPageHeroSection,
  shopifyDevelopmentPageWhyShopifySection,
  shopifyDevelopmentPageScenariosSection,
  shopifyDevelopmentPageHowWeWorkSection,
  shopifyDevelopmentPageTestimonialSection,
  shopifyDevelopmentPageCtaSection,
} from "./pages/shopifyDevelopmentPage";
import {
  shopifyPosPageHeroSection,
  shopifyPosPageFeaturesSection,
  shopifyPosPagePerfectForSection,
  shopifyPosPageCtaSection,
} from "./pages/shopifyPosPage";
import {
  shopifyPlatformPageHeroSection,
  shopifyPlatformPageBleedingMoneySection,
  shopifyPlatformPageShopifyEmpiresSection,
  shopifyPlatformPageRevenueFormSection,
  shopifyPlatformPageSuccessStoriesSection,
} from "./pages/shopifyPlatformPage";
import {
  shopifyPosInfoPageHeroSection,
  shopifyPosInfoPageBleedingMoneySection,
  shopifyPosInfoPageOmnichannelFeaturesSection,
  shopifyPosInfoPageRevenueFormSection,
} from "./pages/shopifyPosInfoPage";
import { shopifyTcoCalculatorPageHeroSection } from "./pages/shopifyTcoCalculatorPage";
import {
  shopifyXPimPageHeroSection,
  shopifyXPimPageWhatIsPimSection,
  shopifyXPimPageIntegratingPimSection,
  shopifyXPimPageWhichBusinessesSection,
  shopifyXPimPageTimeSavingsSection,
  shopifyXPimPageWhyGoodInvestmentSection,
  shopifyXPimCombinedSection,
  shopifyXPimPageCtaSection,
} from "./pages/shopifyXPimPage";
import {
  shopifyXAiPageHeroSection,
  shopifyXAiPageEnhancingWithAiSection,
  shopifyXAiPageHowWeLeverageAiSection,
  shopifyXAiPageAiToolsToolkitSection,
  shopifyXAiPageHowWeApplyAiSection,
  shopifyXAiPageAiEnhancedProcessSection,
  shopifyXAiPageFaqSection,
  shopifyXAiPageCtaSection,
} from "./pages/shopifyXAiPage";
import {
  whyShopifyPageHeroSection,
  whyShopifyPageWhatIsShopifySection,
  whyShopifyPageShopifyFactsSection,
  whyShopifyPageWhyBusinessesChooseSection,
  whyShopifyPageWhyScandicommerceSpecializesSection,
  whyShopifyPageShopifyAiSection,
  whyShopifyPageCtaSection,
} from "./pages/whyShopifyPage";
import {
  landingPage,
  servicesPage,
  aboutPage,
  contactPage,
  workPage,
  blogPage,
  blogPost,
  shopifyDevelopmentPage,
  migratePage,
  shopifyPosPage,
  allPackagesPage,
  shopifyPlatformPage,
  shopifyPosInfoPage,
  shopifyTcoCalculatorPage,
  shopifyXPimPage,
  shopifyXAiPage,
  whyShopifyPage,
  partnersPage,
  partnerCategory,
  packageDetailPage,
  merchPage,
  merchProductSettings,
  headerSettings,
  footerSettings,
  vippsHurtigkassePage,
} from "./pages";

// ============================================
// Export All Schema Types
// ============================================
export const schemaTypes = [
  // Object types
  link,
  button,
  seo,
  blockContent,
  // Blog page builder blocks
  richTextBlock,
  keyTakeawaysBlock,
  statsRowBlock,
  tableBlock,
  comparisonCardsBlock,
  calloutBlock,
  prosConsBlock,
  codeBlock,
  faqBlock,
  ctaBlock,
  gradientTitleBlock,
  imageBlock,
  dividerBlock,

  // Document types
  post,

  // Landing page section blocks (reusable object types)
  heroSection,
  trustedBySection,
  painPointsSection,
  servicesShowcaseSection,
  resultsSection,
  processSection,
  partnersSection,
  ctaSection,
  technicalDepthSection,

  workPageHeroSection,
  workPageCaseStudiesSection,
  workPageCtaSection,
  partnersPageHeroSection,
  partnersPageWhyOurPartnershipSection,
  partnersPagePartnersGridSection,
  partnersPageCtaSection,
  aboutPageHeroSection,
  aboutPageWhyDifferentSection,
  aboutPageOurStorySection,
  aboutPageOurValuesSection,
  aboutPageMeetTheTeamSection,
  aboutPageTrustedPartnershipsSection,
  aboutPageCtaSection,
  contactPageBookingNested,
  contactPageMessageNested,
  contactPageHeroSection,
  contactPageCardsSection,
  contactPageBookingGroupSection,
  contactPageMapSection,
  contactPageFaqSection,

  migratePageHeroSection,
  migratePagePlatformsSection,
  migratePageRisksProtectionSection,
  migratePageProcessSection,
  migratePageResultsSection,
  migratePageCtaSection,
  merchPageHeroSection,
  merchPageQualityShowcaseSection,
  merchPageNewsletterSection,
  blogPageHeroSection,
  blogPageFeaturedArticleSection,
  blogPageArticlesGridSection,
  blogPageNewsletterCtaSection,
  allPackagesPageHeroSection,
  allPackagesPagePackagesSection,
  allPackagesPageFaqSection,
  packageDetailPagePackageInfoSection,
  packageDetailPageHeroButtonsSection,
  packageDetailPageBestForSection,
  packageDetailPageIdealForSection,
  packageDetailPageHighlightsSection,
  packageDetailPageMoreDeliverablesSection,
  packageDetailPageIncludedListSection,
  packageDetailPageIncludedCategoriesSection,
  packageDetailPageProcessStepsSection,
  packageDetailPageFaqListSection,
  packageDetailPageReviewsListSection,
  packageDetailPageTabLabelsSection,
  packageDetailPageAddOnsSection,
  packageDetailPageCaseStudiesBannerSection,
  vippsHurtigkassePageHeroSection,
  vippsHurtigkassePageFeaturesSection,
  vippsHurtigkassePageHowToGetStartedSection,
  vippsHurtigkassePagePricingSection,
  vippsHurtigkassePageOrderFormSection,
  vippsHurtigkassePageSupportSection,
  shopifyDevelopmentPageHeroSection,
  shopifyDevelopmentPageWhyShopifySection,
  shopifyDevelopmentPageScenariosSection,
  shopifyDevelopmentPageHowWeWorkSection,
  shopifyDevelopmentPageTestimonialSection,
  shopifyDevelopmentPageCtaSection,
  shopifyPosPageHeroSection,
  shopifyPosPageFeaturesSection,
  shopifyPosPagePerfectForSection,
  shopifyPosPageCtaSection,
  shopifyPlatformPageHeroSection,
  shopifyPlatformPageBleedingMoneySection,
  shopifyPlatformPageShopifyEmpiresSection,
  shopifyPlatformPageRevenueFormSection,
  shopifyPlatformPageSuccessStoriesSection,
  shopifyPosInfoPageHeroSection,
  shopifyPosInfoPageBleedingMoneySection,
  shopifyPosInfoPageOmnichannelFeaturesSection,
  shopifyPosInfoPageRevenueFormSection,
  shopifyTcoCalculatorPageHeroSection,
  shopifyXPimPageHeroSection,
  shopifyXPimPageWhatIsPimSection,
  shopifyXPimPageIntegratingPimSection,
  shopifyXPimPageWhichBusinessesSection,
  shopifyXPimPageTimeSavingsSection,
  shopifyXPimPageWhyGoodInvestmentSection,
  shopifyXPimCombinedSection,
  shopifyXPimPageCtaSection,
  shopifyXAiPageHeroSection,
  shopifyXAiPageEnhancingWithAiSection,
  shopifyXAiPageHowWeLeverageAiSection,
  shopifyXAiPageAiToolsToolkitSection,
  shopifyXAiPageHowWeApplyAiSection,
  shopifyXAiPageAiEnhancedProcessSection,
  shopifyXAiPageFaqSection,
  shopifyXAiPageCtaSection,
  whyShopifyPageHeroSection,
  whyShopifyPageWhatIsShopifySection,
  whyShopifyPageShopifyFactsSection,
  whyShopifyPageWhyBusinessesChooseSection,
  whyShopifyPageWhyScandicommerceSpecializesSection,
  whyShopifyPageShopifyAiSection,
  whyShopifyPageCtaSection,

  // Page types
  landingPage,
  servicesPage,
  aboutPage,
  contactPage,
  workPage,
  blogPage,
  blogPost,
  shopifyDevelopmentPage,
  migratePage,
  shopifyPosPage,
  allPackagesPage,
  shopifyPlatformPage,
  shopifyPosInfoPage,
  shopifyTcoCalculatorPage,
  shopifyXPimPage,
  shopifyXAiPage,
  whyShopifyPage,
  partnersPage,
  partnerCategory,
  packageDetailPage,
  merchPage,
  merchProductSettings,
  headerSettings,
  footerSettings,
  vippsHurtigkassePage,
  calendlyBooking,
];
